# Generated by Django 5.0.6 on 2024-06-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinMarketCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('contracts', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_chnage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_cap_rank', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_rank', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_change', models.DecimalField(decimal_places=2, max_digits=20)),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('diluted_market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
