# Generated by Django 5.0.6 on 2024-06-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinmarketcap',
            name='price_chnage',
        ),
        migrations.AddField(
            model_name='coinmarketcap',
            name='official_links',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coinmarketcap',
            name='price_change',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coinmarketcap',
            name='socials',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coinmarketcap',
            name='circulating_supply',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coinmarketcap',
            name='diluted_market_cap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coinmarketcap',
            name='market_cap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coinmarketcap',
            name='market_cap_rank',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coinmarketcap',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coinmarketcap',
            name='total_supply',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coinmarketcap',
            name='volume',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coinmarketcap',
            name='volume_change',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coinmarketcap',
            name='volume_rank',
            field=models.CharField(max_length=100),
        ),
    ]
